/**
 * Field Type Metadata
 *
 * Provides metadata and configuration for each field type.
 * Used by the schema builder UI to display appropriate inputs and validation.
 */

import type { SchemaFieldType } from './SchemaDefinition'

export interface FieldTypeMetadata {
  type: SchemaFieldType
  label: string
  description: string
  dataType: string
  icon: string
  color: string
  inputComponent: string
  supportsValidation: boolean
  supportsDefault: boolean
  supportsEnum: boolean
  supportsReference: boolean
  category: 'basic' | 'numeric' | 'datetime' | 'media' | 'relation' | 'advanced'
}

export const FIELD_TYPE_METADATA: Record<SchemaFieldType, FieldTypeMetadata> = {
  text: {
    type: 'text',
    label: 'Text',
    description: 'Short string, single line',
    dataType: 'String',
    icon: 'Type',
    color: 'blue',
    inputComponent: 'Text Input',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  email: {
    type: 'email',
    label: 'Email',
    description: 'Email address with validation',
    dataType: 'string',
    icon: 'Mail',
    color: 'blue',
    inputComponent: 'Input',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  url: {
    type: 'url',
    label: 'URL',
    description: 'Web URL with validation',
    dataType: 'string',
    icon: 'Link',
    color: 'cyan',
    inputComponent: 'Input',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  textarea: {
    type: 'textarea',
    label: 'Textarea',
    description: 'Multi-line text input',
    dataType: 'string',
    icon: 'FileText',
    color: 'purple',
    inputComponent: 'Textarea',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  select: {
    type: 'select',
    label: 'Select',
    description: 'Pre-defined list of choices (Dropdown)',
    dataType: 'string',
    icon: 'List',
    color: 'cyan',
    inputComponent: 'Input',
    supportsValidation: false,
    supportsDefault: true,
    supportsEnum: true,
    supportsReference: false,
    category: 'basic',
  },
  richtext: {
    type: 'richtext',
    label: 'Rich Text',
    description: 'Long-form content, supports formatting',
    dataType: 'String (Markdown/HTML)',
    icon: 'FileText',
    color: 'purple',
    inputComponent: 'WYSIWYG Editor',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  number: {
    type: 'number',
    label: 'Number',
    description: 'Whole integers only',
    dataType: 'Integer',
    icon: 'Hash',
    color: 'green',
    inputComponent: 'Number Input',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'numeric',
  },
  float: {
    type: 'float',
    label: 'Float',
    description: 'Decimal numbers (floating point)',
    dataType: 'Float/Decimal',
    icon: 'Hash',
    color: 'green',
    inputComponent: 'Number Input',
    supportsValidation: true,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'numeric',
  },
  boolean: {
    type: 'boolean',
    label: 'Boolean',
    description: 'True or False',
    dataType: 'Boolean',
    icon: 'ToggleLeft',
    color: 'indigo',
    inputComponent: 'Toggle/Checkbox',
    supportsValidation: false,
    supportsDefault: true,
    supportsEnum: false,
    supportsReference: false,
    category: 'basic',
  },
  date: {
    type: 'date',
    label: 'Date',
    description: 'Date only (no time)',
    dataType: 'Date String (ISO 8601)',
    icon: 'Calendar',
    color: 'orange',
    inputComponent: 'Date Picker',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'datetime',
  },
  time: {
    type: 'time',
    label: 'Time',
    description: 'Time only (no date)',
    dataType: 'Time String',
    icon: 'Clock',
    color: 'orange',
    inputComponent: 'Time Picker',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'datetime',
  },
  datetime: {
    type: 'datetime',
    label: 'Date & Time',
    description: 'Full timestamp',
    dataType: 'DateTime String (ISO 8601)',
    icon: 'CalendarClock',
    color: 'orange',
    inputComponent: 'DateTime Picker',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'datetime',
  },
  currency: {
    type: 'currency',
    label: 'Currency',
    description: 'Number with mandatory currency code',
    dataType: 'Object { value: Number, currency: String }',
    icon: 'DollarSign',
    color: 'emerald',
    inputComponent: 'Number Input with Currency Select',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'numeric',
  },
  media: {
    type: 'media',
    label: 'Media',
    description: 'General file uploads (PDF, ZIP, DOC)',
    dataType: 'Reference ID to media collection',
    icon: 'File',
    color: 'slate',
    inputComponent: 'File Uploader',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  photo: {
    type: 'photo',
    label: 'Photo',
    description: 'Single optimized image upload',
    dataType: 'Reference ID to media collection',
    icon: 'Image',
    color: 'pink',
    inputComponent: 'Image Preview Uploader',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  multiplePhotos: {
    type: 'multiplePhotos',
    label: 'Multiple Photos',
    description: 'Multiple image uploads (gallery)',
    dataType: 'Array of Reference IDs',
    icon: 'Images',
    color: 'pink',
    inputComponent: 'Multi-Image Gallery Uploader',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  video: {
    type: 'video',
    label: 'Video',
    description: 'Single video - embed links or hosted file',
    dataType: 'String (URL) or Reference ID',
    icon: 'Video',
    color: 'red',
    inputComponent: 'URL Input / Video Player',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  multipleVideos: {
    type: 'multipleVideos',
    label: 'Multiple Videos',
    description: 'Multiple video uploads',
    dataType: 'Array of URLs or Reference IDs',
    icon: 'Film',
    color: 'red',
    inputComponent: 'Multi-Video Uploader',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  multipleMedia: {
    type: 'multipleMedia',
    label: 'Multiple Media Files',
    description: 'Multiple general file uploads',
    dataType: 'Array of Reference IDs',
    icon: 'Files',
    color: 'slate',
    inputComponent: 'Multi-File Uploader',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
  json: {
    type: 'json',
    label: 'JSON',
    description: 'Raw data structure',
    dataType: 'JSON/JSONB Object',
    icon: 'Code',
    color: 'yellow',
    inputComponent: 'Code Editor (for raw JSON)',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'advanced',
  },
  uid: {
    type: 'uid',
    label: 'UID (Unique Identifier)',
    description: 'Auto-generated, guaranteed unique string',
    dataType: 'String',
    icon: 'Key',
    color: 'violet',
    inputComponent: 'Auto-filled/Read-only',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'advanced',
  },
  enum: {
    type: 'enum',
    label: 'Enumeration',
    description: 'Pre-defined list of choices (Dropdown)',
    dataType: 'String',
    icon: 'List',
    color: 'cyan',
    inputComponent: 'Select Dropdown',
    supportsValidation: false,
    supportsDefault: true,
    supportsEnum: true,
    supportsReference: false,
    category: 'basic',
  },
  reference: {
    type: 'reference',
    label: 'Single Relation',
    description: 'Link to one entry in another collection',
    dataType: 'Reference ID (String)',
    icon: 'Link',
    color: 'teal',
    inputComponent: 'Searchable Select',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: true,
    category: 'relation',
  },
  multiReference: {
    type: 'multiReference',
    label: 'Multiple Relations',
    description: 'Link to multiple entries in another collection',
    dataType: 'Array of Reference IDs',
    icon: 'Link2',
    color: 'teal',
    inputComponent: 'Multi-Select/Tagging Component',
    supportsValidation: false,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: true,
    category: 'relation',
  },
  svg: {
    type: 'svg',
    label: 'SVG',
    description: 'SVG code/files are uploaded',
    dataType: 'String (SVG Code)',
    icon: 'Shapes',
    color: 'fuchsia',
    inputComponent: 'Code Editor / File Upload',
    supportsValidation: true,
    supportsDefault: false,
    supportsEnum: false,
    supportsReference: false,
    category: 'media',
  },
}

/**
 * Get field type metadata by type
 */
export function getFieldTypeMetadata(type: SchemaFieldType): FieldTypeMetadata {
  return FIELD_TYPE_METADATA[type]
}

/**
 * Get all field types grouped by category
 */
export function getFieldTypesByCategory() {
  const categories = {
    basic: [] as FieldTypeMetadata[],
    numeric: [] as FieldTypeMetadata[],
    datetime: [] as FieldTypeMetadata[],
    media: [] as FieldTypeMetadata[],
    relation: [] as FieldTypeMetadata[],
    advanced: [] as FieldTypeMetadata[],
  }

  Object.values(FIELD_TYPE_METADATA).forEach((metadata) => {
    categories[metadata.category].push(metadata)
  })

  return categories
}
